name: newspaper_app_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dio: ^5.8.0+1
  intl: ^0.18.0
  path: ^1.9.0
  logger: ^2.5.0
  lottie: ^3.3.1
  shimmer: ^3.0.0
  sqflite: ^2.4.2
  http_parser: ^4.1.2
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  file_picker: ^10.0.0
  flutter_animate: ^4.5.2
  dropdown_button2: ^2.3.9
  connectivity_plus: ^6.1.3
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.4.1
  flutter_secure_storage: ^9.2.4
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
    - assets/png/
    - assets/jpg/
    - assets/json/

  uses-material-design: true



